# Generated by Django 4.1.4 on 2023-01-26 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='Post_images')),
                ('image2', models.ImageField(null=True, upload_to='Post_images')),
                ('image3', models.ImageField(null=True, upload_to='Post_images')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file1', models.FileField(upload_to='files')),
                ('thumbnail', models.ImageField(default='', upload_to='Post_front_images')),
                ('day', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
