# Generated by Django 4.1.4 on 2023-01-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_gender_remove_profile_univ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Profile_images/blank.webp', upload_to='Profile_images'),
        ),
    ]
