# Generated by Django 4.1.4 on 2023-01-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_images',
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(null=True, upload_to='Post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(null=True, upload_to='Post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(null=True, upload_to='Post_images'),
        ),
    ]
