# Generated by Django 4.1.4 on 2023-01-26 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_post_images_post_image1_post_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 26)),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.CharField(blank=True, default='Thursday', max_length=100),
        ),
    ]
