# Generated by Django 4.1.4 on 2023-01-26 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_date_alter_post_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 23, 58, 12, 832195)),
        ),
    ]
