# Generated by Django 4.1.4 on 2023-01-26 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 0, 6, 59, 757956)),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.CharField(default='Friday', max_length=100),
        ),
    ]
