# Generated by Django 4.1.4 on 2023-01-26 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_date_alter_post_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 0, 13, 33, 638074)),
        ),
        migrations.AlterField(
            model_name='post',
            name='day',
            field=models.CharField(default=26, max_length=100),
        ),
    ]
